POST http://localhost:3000
Content-Type: application/json

{
    "nome": "fdgdgfdfg",
    "email": "",
    "senha": "zgfdgdf",
    "role": "admin",
    "confirmarSenha": "zgfdgdf"
}

###
GET http://localhost:3000/users

###
GET http://localhost:3000/user/67e198515fd22e60ffcf7faa

###
POST http://localhost:3000/auth
Content-Type: application/json

{
    "email": "ggggggg@gmail.com",
    "senha": "zgfdgdf"
}

###
DELETE http://localhost:3000/remove
Authorization: Bearer token