POST http://localhost:3000
Content-Type: application/json

{
    "nome": "fdgdgfdfg",
    "email": "ggggggg@gmail.com",
    "senha": "zgfdgdf",
    "role": "admin",
    "confirmarSenha": "zgfdgdf"
}

###
GET http://localhost:3000/users

###
GET http://localhost:3000/user/67e198515fd22e60ffcf7fbb